import random
import uuid

import requests
from locust import HttpUser, between, events, task


LOAD_TEST_EMAIL = "locust_loadtest@example.com"
LOAD_TEST_USERNAME = "locust_loadtest"
LOAD_TEST_PASSWORD = "StrongPass123!"


@events.test_start.add_listener
def prepare_load_test_user(environment, **kwargs):
    environment.created_project_ids = []
    requests.post(
        f"{environment.host}/auth/register",
        json={
            "email": LOAD_TEST_EMAIL,
            "username": LOAD_TEST_USERNAME,
            "password": LOAD_TEST_PASSWORD,
        },
        timeout=10,
    )
    response = requests.post(
        f"{environment.host}/auth/login",
        json={"email": LOAD_TEST_EMAIL, "password": LOAD_TEST_PASSWORD},
        timeout=10,
    )
    response.raise_for_status()
    environment.shared_access_token = response.json()["access_token"]


@events.test_stop.add_listener
def cleanup_load_test_projects(environment, **kwargs):
    token = getattr(environment, "shared_access_token", None)
    project_ids = getattr(environment, "created_project_ids", [])
    if not token:
        return

    headers = {"Authorization": f"Bearer {token}"}
    for project_id in set(project_ids):
        requests.delete(
            f"{environment.host}/projects/{project_id}",
            headers=headers,
            timeout=10,
        )


class BlockTestUser(HttpUser):
    wait_time = between(1, 5)

    def on_start(self):
        self.email = LOAD_TEST_EMAIL
        self.password = LOAD_TEST_PASSWORD
        self.project_ids = []
        self.test_ids = []
        self.token = self.environment.shared_access_token

    def auth_headers(self):
        return {"Authorization": f"Bearer {self.token}"}

    @task(4)
    def view_dashboard(self):
        if not self.token:
            return
        headers = self.auth_headers()
        self.client.get("/stats/overview", headers=headers, name="/stats/overview")
        self.client.get("/projects", headers=headers, name="/projects")

    @task(2)
    def view_profile(self):
        if not self.token:
            return
        self.client.get("/auth/me", headers=self.auth_headers(), name="/auth/me")

    @task(1)
    def create_project_and_test(self):
        if not self.token:
            return

        headers = self.auth_headers()
        with self.client.post(
            "/projects",
            json={
                "name": f"Load Test Project {uuid.uuid4().hex[:6]}",
                "description": "Generated by Locust load test",
            },
            headers=headers,
            catch_response=True,
            name="/projects (POST)",
        ) as response:
            if response.status_code == 201:
                project_id = response.json().get("id")
                self.project_ids.append(project_id)
                self.environment.created_project_ids.append(project_id)
                response.success()
            else:
                response.failure(f"Failed to create project: {response.text}")
                return

        with self.client.post(
            f"/projects/{project_id}/tests",
            json={
                "name": f"Load Test {uuid.uuid4().hex[:6]}",
                "description": "Locust test scenario",
                "scenario": "Basic load-test scenario",
                "docker_image": "python:3.12-slim",
                "command": "python -c \"print('locust ok')\"",
            },
            headers=headers,
            catch_response=True,
            name="/projects/{id}/tests (POST)",
        ) as response:
            if response.status_code == 201:
                test_id = response.json().get("id")
                self.test_ids.append(test_id)
                response.success()
            else:
                response.failure(f"Failed to create test: {response.text}")

    @task(3)
    def view_project_details(self):
        if not self.token or not self.project_ids:
            return
        project_id = random.choice(self.project_ids)
        headers = self.auth_headers()
        self.client.get(f"/projects/{project_id}", headers=headers, name="/projects/{id} (GET)")
        self.client.get(
            f"/projects/{project_id}/tests",
            headers=headers,
            name="/projects/{id}/tests (GET)",
        )

    @task(2)
    def chat_in_test(self):
        if not self.token or not self.test_ids:
            return
        test_id = random.choice(self.test_ids)
        headers = self.auth_headers()
        self.client.get(f"/tests/{test_id}/chat", headers=headers, name="/tests/{id}/chat (GET)")
        self.client.post(
            f"/tests/{test_id}/chat",
            json={"message": "Hello from Locust load test"},
            headers=headers,
            name="/tests/{id}/chat (POST)",
        )

    @task(2)
    def view_runs(self):
        if not self.token:
            return
        self.client.get("/runs", headers=self.auth_headers(), name="/runs (GET)")
